// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC20MnhBjTFlajExCz0XZrK0-p7si0sTjY',
    appId: '1:212751703381:web:2203dee25959822f4aa3dc',
    messagingSenderId: '212751703381',
    projectId: 'instagram-clone-ae8fd',
    authDomain: 'instagram-clone-ae8fd.firebaseapp.com',
    storageBucket: 'instagram-clone-ae8fd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkNZTTj5sCE6rLpapKpoPlyB1EgCAxQgk',
    appId: '1:212751703381:android:f73b181d0d03b3854aa3dc',
    messagingSenderId: '212751703381',
    projectId: 'instagram-clone-ae8fd',
    storageBucket: 'instagram-clone-ae8fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlGhyOk5J5EZuxZoFIW1w4-M3yAcuFgiE',
    appId: '1:212751703381:ios:7142463f2220b44c4aa3dc',
    messagingSenderId: '212751703381',
    projectId: 'instagram-clone-ae8fd',
    storageBucket: 'instagram-clone-ae8fd.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC20MnhBjTFlajExCz0XZrK0-p7si0sTjY',
    appId: '1:212751703381:web:807631604b4bc2ff4aa3dc',
    messagingSenderId: '212751703381',
    projectId: 'instagram-clone-ae8fd',
    authDomain: 'instagram-clone-ae8fd.firebaseapp.com',
    storageBucket: 'instagram-clone-ae8fd.appspot.com',
  );
}
